# ==========================================
# kafka-service.yaml
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: payment-webhook
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: controller
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app.kubernetes.io/name: kafka

---