# ==========================================
# kafka-configmap.yaml
# ==========================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: payment-webhook
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/managed-by: argocd
data:
  server.properties: |
    # KRaft mode configuration (no ZooKeeper)
    process.roles=broker,controller
    node.id=1
    controller.quorum.voters=1@kafka-service:9093
    
    # Listeners
    listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    inter.broker.listener.name=PLAINTEXT
    advertised.listeners=PLAINTEXT://kafka-service:9092
    controller.listener.names=CONTROLLER
    
    # Cluster settings
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    default.replication.factor=1
    min.insync.replicas=1
    
    # Log settings
    log.dirs=/kafka-logs
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    
    # Log retention
    log.retention.hours=168
    log.retention.check.interval.ms=300000
    log.segment.bytes=1073741824
    
    # Other settings
    group.initial.rebalance.delay.ms=0
    auto.create.topics.enable=true

---