apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service-webhook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DAMMAK/payment-service-webhook.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: payment-webhook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true