apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-webhook-config
  namespace: payment-webhook
data:
  # Database configuration
  db.host: "postgres-service"
  db.port: "5432"
  db.name: "webhook_db"
  
  # Redis configuration
  redis.host: "redis-service"
  redis.port: "6379"
  
  # Kafka configuration
  kafka.bootstrap-servers: "kafka-service:9092"
  
  # Security configuration
  jwt.issuer-uri: "http://auth-service:8080/auth/realms/payment"
  
  # Application configuration
  server.port: "8080"
  logging.level.com.payment.webhook: "INFO"