apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: default
data:
  application-kubernetes.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://postgres-service:5432/payment_webhook_db
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      flyway:
        enabled: true
        baseline-on-migrate: true
      redis:
        host: redis-service
        port: 6379