# ==========================================
# ingress.yaml (Alternative to LoadBalancer)
# ==========================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-webhook-ingress
  namespace: payment-webhook
  labels:
    app.kubernetes.io/name: payment-service-webhook
    app.kubernetes.io/managed-by: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - payment-webhook.yourdomain.com
      secretName: payment-webhook-tls
  rules:
    - host: payment-webhook.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-service-webhook
                port:
                  number: 80

---