apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payment-webhook

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml