apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payment-webhook

resources:
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - kafka-deployment.yaml
  - zookeeper-deployment.yaml
  - deployment.yaml
  - service.yaml
  - argocd-application.yaml