# ==========================================
# service-monitor.yaml (For Prometheus monitoring)
# ==========================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-service-monitor
  namespace: payment-webhook
  labels:
    app.kubernetes.io/name: payment-service-webhook
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service-webhook
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s

---