apiVersion: v1
kind: Service
metadata:
  name: payment-service-webhook
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: payment-service-webhook