# ==========================================
# service.yaml
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: payment-service-webhook
  namespace: payment-webhook
  labels:
    app.kubernetes.io/name: payment-service-webhook
    app.kubernetes.io/managed-by: argocd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: payment-service-webhook
  sessionAffinity: None

---